#! /usr/bin/env php
<?php

/** @var \Composer\Autoload\ClassLoader $loader */
$loader = require __DIR__ . '/../vendor/autoload.php';
$loader->addPsr4('app\\', __DIR__ . '/src');

$server = new blink\server\CliServer([
    'bootstrap' => __DIR__ . '/src/bootstrap.php'
]);

exit($server->run());
